### ISSUE TITLE
2bugs

### ISSUE THREAD

**Issue by R1card0-tutu** [K1p2y3/Tencent_Yun_tools#1]
1.Regions_list.append(str(s["InstanceSet"][0]["Placement"]["Zone"]))
2.tencentcloud.common.exception.tencent_cloud_sdk_exception.TencentCloudSDKException: [TencentCloudSDKException] code:InvalidParameterValue message:参数 `X-TC-Region` 取值错误。 requestId:

**Comment by K1p2y3** [comment]
地域信息填写错误，例如 北京地区 就直接 ap-beijing

**Comment by K1p2y3** [comment]
改了
